### ISSUE TITLE
Undefined symbol: typeinfo for ncnn::Layer

### ISSUE THREAD

**Issue by Xxxxi** [cmdbug/cmdbug#1]
ios端 同时用到了OCR以及ncnn，运行工程报Undefined symbol: typeinfo for ncnn::Layer，请问要如何解决，不修改Enable C++ Runtime Types 这个参数要怎么确保这两个功能能同时调用

**Comment by cmdbug** [comment]
https://github.com/cmdbug/YOLOv5_NCNN/issues/72
